### ISSUE TITLE
Cannot install python-llm

### ISSUE THREAD

**Issue by akshayvkt** [danielgross/python-llm#2]
I get the error that requirements.txt can't be found, although the requirements file is in the same directory as setup.py
I've also tried installing it in venv, but get the same error. I wasn't sure if its a permissions issue, but i wanted to flag it so someone could help me with this.

<img width="1311" alt="image" src="https://github.com/danielgross/python-llm/assets/64036106/e11878ee-fbe8-4f8f-9445-408e62e40090">

**Comment by vektroi-d** [comment]
Receiving the same error across multiple setups.

**Comment by danielgross** [comment]
Hi there, sorry for the bug, this is fixed in 0.1.7.

**Comment by akshayvkt** [comment]
works now, thank you!
